apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-certs
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgresql.crt: {{ default "" .Values.sslCert | b64enc | quote }}
  postgresql.key: {{ default "" .Values.sslKey | b64enc | quote }}
  root.crt: {{ default "" .Values.sslRootCrt | b64enc | quote }}
