apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.loadBalancerType }}
  annotations: 
    cloud.google.com/load-balancer-type: {{ .Values.loadBalancerType }}
  {{- end }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  {{- if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
  {{- end }}
  {{- if .Values.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ .Values.loadBalancerSourceRanges }}
  {{- end }}
  ports:
    - name: pgbouncer
      port: 5432
      protocol: TCP
      targetPort: pgbouncer
  selector:
    app: {{ .Release.Name }}
